SCHEMA_VERSION=1
PROFILE=frontend
JIRA_PROJECT_KEY=BF
JIRA_BOARD_ID=35
CONFLUENCE_SPACE_KEY=Berokafron
CONFLUENCE_ROOT_CONTENT_ID=65831203
CONFLUENCE_ROOT_CONTENT_TYPE=page
INTEGRATION_PROFILE=beroka-be-fe
CROSS_REPO_POLICY=profile-controlled
