SCHEMA_VERSION=1
PROFILE=backend
JIRA_PROJECT_KEY=BB
JIRA_BOARD_ID=34
CONFLUENCE_SPACE_KEY=Berokaback
CONFLUENCE_ROOT_CONTENT_ID=65962274
CONFLUENCE_ROOT_CONTENT_TYPE=page
INTEGRATION_PROFILE=beroka-be-fe
CROSS_REPO_POLICY=profile-controlled
